### ISSUE TITLE
Модификация Deerma-F600

### ISSUE THREAD

**Issue by kkdkkd1** [Brokly/ESPHome-Humidifier-Deerma-F600#3]
В моём увлажнителе Deerma DEM-F600, включение/выключение увлажнителя реализовано кратковременным нажатием на основной сенсор, а режимы работы переключаются кратковременным нажатием второго сенсора. А если второй сенсор зажать на 3 сек. устанавливается таймер и время выключения.
Понятно, что надо второй сенсор также подключить, а с программированием сможете помочь?

**Comment by Brokly** [comment]
К сожалению этот проект не предполагал охват всех увлажнителей, просто не обладаю необходимым , для этого временем. Подсказать что то по своему  коду могу, но дорабатывать не возьмусь.
